name: Test

on:
  push:
    branch:
      - master

jobs:
  coding-style:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
    - name: Hello
      run: echo Hello World

    - name: Check secret value
      run: echo ${{ secrets.MY_SUPER_CREDENTIAL }} | sha256
